---

version: '3.2'
services:
  web:
    container_name: chat_release
    build:
      context: ./
      dockerfile: Dockerfile_release
      args:
        - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    ports:
      - '4000:4000'
    command: bin/react_chat start
