FROM elixir:1.13.4-alpine AS build

ARG SECRET_KEY_BASE

ENV MIX_ENV="prod"
ENV SECRET_KEY_BASE=${SECRET_KEY_BASE}

RUN apk add --no-cache build-base git npm yarn python3

RUN mix local.hex --force && \
  mix local.rebar --force

COPY ./react_chat /app

WORKDIR /app

RUN mix deps.get --only prod

RUN cd assets && yarn install

RUN mix assets.deploy

RUN mix phx.gen.release

RUN mix release

FROM alpine:3.15.4 AS app

ENV MIX_ENV="prod"
ENV HOME=/app
ENV PHX_SERVER=true

RUN apk add --no-cache openssl ncurses-libs curl jq libstdc++

WORKDIR /app

RUN chown nobody:nobody /app

USER nobody:nobody

COPY --from=build --chown=nobody:nobody /app/_build/${MIX_ENV}/rel/react_chat ./

CMD ["bin/react_chat", "start"]
