---

version: '3.2'
services:
  web:
    container_name: chat_release
    build:
      context: ./
      dockerfile: Dockerfile_release
      args:
        - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    ports:
      - '4000:4000'
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - AUTH0_DOMAIN
      - AUTH0_CLIENT_ID
      - SECRET_KEY_BASE
    command: bin/react_chat start
